# Site settings
# in the templates available like {{ site.myvariable }}.
title: Rob Ruiz personal page.
email: Robert.S.Ruiz@gmail.com
brand: Rob Ruiz
headline: Tinkerer, Developer and Futurist
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://RobRuiz.me" # the base hostname & protocol for your site
copyright: 2016 Rob Ruiz. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: Robert.S.Ruiz@gmail.com
phone: (813) 516-8543
